---
- name: Add icingaweb2 group
  group: name=icingaweb2 state=present system=yes
  
- name: add user www-data to group icingaweb2
  user: name=www-data groups=icingaweb2 append=yes

- name: Enable icinga 2 command feature
  shell: icinga2 feature enable command
  notify: restart icinga2

- name: Enable icinga 2 ido-mysql feature
  shell: icinga2 feature enable ido-mysql

- name: Enable icinga 2 statusdata feature
  shell: icinga2 feature enable statusdata

- name: Create icingaweb2 database
  when: apt|success
  register: icingawebdb
  mysql_db: name=icingaweb2 state=present login_user=root

- name: Create db user icingaweb2
  when: icingawebdb|success
  mysql_user: name=icingaweb2 password=bclan2016 priv=icingaweb2.*:ALL state=present

- name: Download nagircbot
  unarchive: src=https://www.vanheusden.com/nagircbot/nagircbot-0.0.33.tgz dest=/usr/src copy=no owner=nagios

- name: compile nagircbot
  shell: make
  register: nibcompiled
  args:
    chdir: /usr/src/nagircbot-0.0.33

- name: install nagircbot
  when: nibcompiled|success
  register: nibinstalled
  shell: make install
  args:
    chdir: /usr/src/nagircbot-0.0.33

- name: Add IRC Bot service
  when: nibinstalled|success
  register: nibservice
  template: src=nagircbot.service.j2 dest=/etc/systemd/system/nagircbot.service owner=root group=root

- name: reload systemd
  command: systemctl daemon-reload

- name: Enable IRC Bot service
  when: nibservice|success
  service: name=nagircbot enabled=yes
  notify:
   - start nagircbot
