---
- name: Add custom hosts
  when: apt|success
  register: librenmsconf
  template: src=icinga-hosts.conf.j2 dest=/etc/icinga2/conf.d/hosts.conf owner=root group=root

- name: Add custom services
  when: apt|success
  register: librenmsconf
  template: src=icinga-services.conf.j2 dest=/etc/icinga2/conf.d/services.conf owner=root group=root

- name: Add icingaweb2 group
  group: name=icingaweb2 state=present system=yes
  
- name: add user www-data to group icingaweb2
  user: name=www-data groups=icingaweb2 append=yes

- name: Enable icinga 2 command feature
  shell: icinga2 feature enable command
  notify: restart icinga2

- name: Enable icinga 2 ido-mysql feature
  shell: icinga2 feature enable ido-mysql

- name: Enable icinga 2 statusdata feature
  shell: icinga2 feature enable statusdata

- name: Create icingaweb2 database
  when: apt|success
  register: icingawebdb
  mysql_db: name=icingaweb2 state=present login_user=root

- name: Create db user icingaweb2
  when: icingawebdb|success
  mysql_user: name=icingaweb2 password=bclan2016 priv=icingaweb2.*:ALL state=present
  
- name: setting owner
  file: path=/etc/icingaweb2/modules state=directory recurse=yes owner=www-data group=icingaweb2 mode=0775