---
- name: Stop ngircd
  service: name=ngircd state=stopped

- name: Enable IRC Server service
  service: name=ngircd enabled=yes
  notify:
   - start ngircd
   
- name: Copy ngircd config files
  copy: src=ngircd/ dest=/etc/ngircd/ owner=root group=root