---
- include: system.yml
- include: nginx.yml
- include: icinga.yml
- include: librenms.yml

- name: Icinga Installation finished 
  debug: msg="Now generate a token with 'icingacli setup token create' and go at http:/{{ domain_iw }}/icingaweb2/setup to continue the installation"

- name: LibreNMS Installation finished 
  debug: msg="Now go to http:/{{ domain_ln }} to continue the installation"