---
- name: Add Debmon repo
  apt_repository: repo='deb http://debmon.org/debmon debmon-jessie main' state=present
  register: aptrepo

- name: Add Debmon repo
  when: aptrepo|success
  apt_key: url=http://debmon.org/debmon/repo.key state=present
  register: aptrepokey

- name: Install icinga2,icingaweb2,nginx,php5-fpm,mariadb + dep
  when: aptrepokey|success
  apt: name={{ item }} state=installed update_cache=yes install_recommends=no
  with_items:
    - ca-certificates
    - icinga2
    - icinga2-ido-mysql
    - icingaweb2
    - nginx
    - php5-fpm
    - mariadb-server
    - mariadb-client
    - python-mysqldb
    - php5-cli
    - php5-mysql
    - php5-gd
    - php5-snmp
    - php-pear
    - php5-curl
    - snmp
    - graphviz
    - php5-mcrypt
    - php5-json
    - fping
    - imagemagick
    - whois
    - nmap
    - php-net-ipv4
    - php-net-ipv6
    - rrdtool
    - git
  register: apt
  notify:
    - start nginx

- name: Add librenms user
  user: name=librenms createhome=no system=yes comment="librenms 3 User" shell=/sbin/nologin home=/opt/librenms
  register: lnuser

- name: Disable Default Site
  when: apt|success
  file: dest=/etc/nginx/sites-enabled/default state=absent

- name: Add icinga nginx Config
  when: apt|success
  register: icingaconf
  template: src=icinga.j2 dest=/etc/nginx/sites-available/{{ domain_iw }}.conf owner=root group=root

- name: Add librenms nginx Config
  when: apt|success
  register: librenmsconf
  template: src=librenms.j2 dest=/etc/nginx/sites-available/{{ domain_ln }}.conf owner=root group=root

- name: Enable nginx Icinga web Config
  when: icingaconf|success
  file: src=/etc/nginx/sites-available/{{ domain_iw }}.conf dest=/etc/nginx/sites-enabled/{{ domain_iw }}.conf state=link
  
- name: Enable nginx librenms Config
  when: librenmsconf|success
  file: src=/etc/nginx/sites-available/{{ domain_ln }}.conf dest=/etc/nginx/sites-enabled/{{ domain_ln }}.conf state=link

- name: Create Web Roots
  when: apt|success
  register: webrootcreated
  file: dest=/var/www/{{ domain_iw }}/public mode=775 state=directory owner=www-data group=www-data

- name: Create icingaweb logdirectory
  when: webrootcreated|success
  file: dest=/var/www/{{ domain_iw }}/logs mode=755 state=directory owner=www-data group=www-data

- name: Web root permissions
  when: webrootcreated|success
  file: dest=/var/www/{{ domain_iw }} mode=775 state=directory owner=www-data group=www-data recurse=yes
  notify:
    - reload nginx

- name: Add index.html redirect
  when: apt|success
  register: librenmsconf
  template: src=index.j2 dest=/var/www/{{ domain_iw }}/public/index.html owner=www-data group=www-data

- name: Create librenms database
  when: apt|success
  register: librenmsdb
  mysql_db: name=librenms state=present login_user=root

- name: Create icinga database
  when: apt|success
  register: icingadb
  mysql_db: name=icinga state=present login_user=root

- name: Create icingaweb2 database
  when: apt|success
  register: icingawebdb
  mysql_db: name=icingaweb2 state=present login_user=root

- name: Create db user librenms
  when: librenmsdb|success
  mysql_user: name=librenms password=bclan2016 priv=librenms.*:ALL state=present

- name: Create db user icinga
  when: icingadb|success
  mysql_user: name=icinga password=bclan2016 priv=icinga.*:ALL state=present

- name: Create db user icingaweb2
  when: icingawebdb|success
  mysql_user: name=icingaweb2 password=bclan2016 priv=icingaweb2.*:ALL state=present

- name: Clone the librenms repo
  when: lnuser|success
  git: repo=https://github.com/librenms/librenms.git dest=/opt/librenms
  register: lncheckout

- name: creating rrd directory
  when: lncheckout|success
  file: path=/opt/librenms/rrd state=directory

- name: setting owner
  when: lncheckout|success
  file: path=/opt/librenms state=directory recurse=yes owner=librenms group=librenms

- name: creating logs directory
  when: lncheckout|success
  file: path=/opt/librenms/logs state=directory owner=www-data group=www-data

# - name: importing databasescheme
  # when: databases|success
  # register: dbschema
  
