---
- name: Download nagircbot
  unarchive: src=https://www.vanheusden.com/nagircbot/nagircbot-0.0.33.tgz dest=/usr/src copy=no owner=nagios

- name: compile nagircbot
  shell: make
  register: nibcompiled
  args:
    chdir: /usr/src/nagircbot-0.0.33

- name: install nagircbot
  when: nibcompiled|success
  register: nibinstalled
  shell: make install
  args:
    chdir: /usr/src/nagircbot-0.0.33

- name: Add IRC Bot service
  when: nibinstalled|success
  register: nibservice
  template: src=nagircbot.service.j2 dest=/etc/systemd/system/nagircbot.service owner=root group=root

- name: reload systemd
  command: systemctl daemon-reload

- name: Enable IRC Bot service
  when: nibservice|success
  service: name=nagircbot enabled=yes
  notify:
   - start nagircbot
