---
- name: Disable Default Site
  when: apt|success
  file: dest=/etc/nginx/sites-enabled/default state=absent

- name: Add icinga nginx Config
  when: apt|success
  register: icingaconf
  template: src=icinga.j2 dest=/etc/nginx/sites-available/{{ domain_iw }}.conf owner=root group=root

- name: Add librenms nginx Config
  when: apt|success
  register: librenmsconf
  template: src=librenms.j2 dest=/etc/nginx/sites-available/{{ domain_ln }}.conf owner=root group=root

- name: Enable nginx Icinga web Config
  when: icingaconf|success
  file: src=/etc/nginx/sites-available/{{ domain_iw }}.conf dest=/etc/nginx/sites-enabled/{{ domain_iw }}.conf state=link

- name: Enable nginx librenms Config
  when: librenmsconf|success
  file: src=/etc/nginx/sites-available/{{ domain_ln }}.conf dest=/etc/nginx/sites-enabled/{{ domain_ln }}.conf state=link

- name: Create Web Roots
  when: apt|success
  register: webrootcreated
  file: dest=/var/www/{{ domain_iw }}/public mode=775 state=directory owner=www-data group=www-data

- name: Create icingaweb logdirectory
  when: webrootcreated|success
  file: dest=/var/www/{{ domain_iw }}/logs mode=755 state=directory owner=www-data group=www-data

- name: Web root permissions
  when: webrootcreated|success
  file: dest=/var/www/{{ domain_iw }} mode=775 state=directory owner=www-data group=www-data recurse=yes
  notify:
    - reload nginx

- name: Add index.html redirect
  when: apt|success
  register: librenmsconf
  template: src=index.j2 dest=/var/www/{{ domain_iw }}/public/index.html owner=www-data group=www-data

- name: Edit the php.ini
  when: apt|success
  template: src=php.ini.j2 dest=/etc/php5/fpm/php.ini owner=root group=root
  notify:
    - restart php-fpm
