---
- name: Disable Default Site
  when: apt|success
  file: dest=/etc/nginx/sites-enabled/default state=absent

- name: Add icinga nginx Config
  when: apt|success
  register: icingaconf
  template: src=nginx-icinga.conf.j2 dest=/etc/nginx/sites-available/{{ icinga.domain }}.conf owner=root group=root

- name: Add dashboard nginx Config
  when: apt|success
  register: dashboardconf
  template: src=nginx-dashboard.conf.j2 dest=/etc/nginx/sites-available/{{ dashboard.domain }}.conf owner=root group=root

- name: Add librenms nginx Config
  when: apt|success
  register: librenmsconf
  template: src=nginx-librenms.conf.j2 dest=/etc/nginx/sites-available/{{ librenms.domain }}.conf owner=root group=root

- name: Enable nginx Icinga web Config
  when: icingaconf|success
  file: src=/etc/nginx/sites-available/{{ icinga.domain }}.conf dest=/etc/nginx/sites-enabled/{{ icinga.domain }}.conf state=link

- name: Enable nginx librenms Config
  when: librenmsconf|success
  file: src=/etc/nginx/sites-available/{{ librenms.domain }}.conf dest=/etc/nginx/sites-enabled/{{ librenms.domain }}.conf state=link

- name: Enable nginx dashboard Config
  when: librenmsconf|success
  file: src=/etc/nginx/sites-available/{{ dashboard.domain }}.conf dest=/etc/nginx/sites-enabled/{{ dashboard.domain }}.conf state=link

- name: Create Dashboard www-root
  when: apt|success
  file: dest=/var/www/{{ dashboard.domain }}/public mode=775 state=directory owner=www-data group=www-data
  
- name: Create Dashboard logs-root
  when: apt|success
  file: dest=/var/www/{{ dashboard.domain }}/logs mode=775 state=directory owner=www-data group=www-data

- name: Create Icingaweb 2 www-root
  when: apt|success
  register: iw_webrootcreated
  file: dest=/var/www/{{ icinga.domain }}/public mode=775 state=directory owner=www-data group=www-data

- name: Create Icingaweb 2 logs-root
  when: iw_webrootcreated|success
  file: dest=/var/www/{{ icinga.domain }}/logs mode=755 state=directory owner=www-data group=www-data

#- name: Icingaweb 2 root permissions
#  when: iw_webrootcreated|success
#  file: dest=/var/www/{{ icinga.domain }} mode=775 state=directory owner=www-data group=www-data recurse=yes
#  notify:
#    - reload nginx

- name: Copy {{ dashboard.domain }} files
  copy: src=dashboard_files/ dest=/var/www/dashboard.lan/public/ owner=www-data group=www-data

- name: Creating dashboard index.php
  template: src=dashboard-index.php.j2 dest=/var/www/{{ dashboard.domain }}/public/index.php owner=www-data group=www-data

- name: Add index.html redirect
  when: apt|success
  register: librenmsconf
  template: src=index.j2 dest=/var/www/{{ icinga.domain }}/public/index.html owner=www-data group=www-data
  notify:
    - reload nginx

- name: Edit the php.ini
  when: apt|success
  template: src=php.ini.j2 dest=/etc/php5/fpm/php.ini owner=root group=root
  notify:
    - restart php-fpm
