---
- name: Add Debmon repo
  apt_repository: repo='deb http://debmon.org/debmon debmon-jessie main' state=present
  register: aptrepo

- name: Add Debmon repo
  when: aptrepo|success
  apt_key: url=http://debmon.org/debmon/repo.key state=present
  register: aptrepokey

- name: Install icinga2,icingaweb2, mariadb + dep
  when: aptrepokey|success
  apt: name={{ item }} state=installed update_cache=yes install_recommends=no
  with_items:
    - ca-certificates
    - cron
    - icinga2
    - icinga2-ido-mysql
    - monitoring-plugins
    - nagios-nrpe-plugin
    - icingaweb2
    - icingaweb2-module-monitoring
    - icingacli
    - mariadb-server
    - mariadb-client
    - python-mysqldb
    - snmp
    - graphviz
    - fping
    - imagemagick
    - whois
    - nmap
    - rrdtool
    - git
    - g++
    - gcc
    - make
    - libssl-dev
    - ngircd
  register: apt
  notify:
    - start nginx

