---
- name: start nginx
  service: name=nginx state=started

- name: reload nginx
  service: name=nginx state=reloaded
  
- name: restart php-fpm
  service: name=php5-fpm state=restarted

- name: restart icinga2
  service: name=icinga2 state=restarted
  
- name: start ngircd
  service: name=ngircd state=started

- name: start nagircbot
  service: name=nagircbot state=started