---
- name: Add ympd nginx Config
  when: ympdservice|success
  register: ngnxconf
  template: src=nginx-mpd.conf.j2 dest=/etc/nginx/sites-available/{{ domain_mpd }}.conf owner=root group=root
  notify:
    - restart nginx

- name: Enable nginx Config
  when: ngnxconf|success
  file: src=/etc/nginx/sites-available/{{ domain_mpd }}.conf dest=/etc/nginx/sites-enabled/{{ domain_mpd }}.conf state=link
