---
- name: Add {{ user }} user
  user: name={{ user }} createhome=yes comment="WebIRC User"
  register: useradded
  
- name: check if kiwiirc already installed
  stat: path=/home/{{ user }}/KiwiIRC/kiwi
  register: st

- name: Clone the kiwiirc repo
  when: useradded|success and not st.stat.exists
  git: repo=https://github.com/prawnsalad/KiwiIRC.git dest=/home/{{ user }}//KiwiIRC
  register: gitcheckout
  
- name: installing dependencies
  when: gitcheckout|success
  shell: npm install
  args:
    chdir: /home/{{user }}/KiwiIRC
  register: npmdep

- name: Add config.js
  when: npmdep|success
  register: kiwiconf
  template: src=config.js.j2 dest=/home/{{user }}/KiwiIRC/config.js  owner={{ user }} group={{ user }}

- name: build client code
  when: kiwiconf|success
  shell: /home/{{ user }}/KiwiIRC/kiwi build
  args:
    chdir: /home/{{user }}/KiwiIRC
  register: kiwibuilt

- name: setting permissions
  file: path=/home/{{ user }} state=directory recurse=yes owner={{ user }} group={{ user }} mode=0750

- name: Add kiwiirc service
  template: src=kiwiirc.service.j2 dest=/etc/systemd/system/kiwiirc.service owner=root group=root
  register: kiwiircservice
  notify:
    - start kiwiirc

- name: reload systemd
  command: systemctl daemon-reload

- name: Enable kiwiirc service
  when: kiwiircservice|success
  service: name=kiwiirc enabled=yes
