---
- name: Add tmnf user
  user: name={{ user }} createhome=yes comment="Trackmania Server User"
  register: useradded

- name: Download Trackmania Nations Forever dedicated server
  when: useradded|success
  unarchive: src={{ dedicated_srv_dl_url }} dest=/home/{{ user }} copy=no owner={{ user }} group={{ user }}

- name: Create dedicated_cfg.txt
  template: src=dedicated_cfg.txt.j2 dest=/home/{{ user }}/GameData/Config/dedicated_cfg.txt owner={{ user }} group={{ user }} mode=0770

- name: Create tracklist
  template: src=tracklist.txt.j2 dest=/home/{{ user }}/GameData/Tracks/MatchSettings/tracklist.txt owner={{ user }} group={{ user }} mode=0770

- name: setting owner back to {{ user }}
  file: path=/home/{{ user }} state=directory recurse=yes owner={{ user }} group={{ user }} mode=0770

- name: Add tmsrv service
  template: src=tmsrv.service.j2 dest=/etc/systemd/system/tmsrv.service owner=root group=root
  register: tmsrvservice

- name: reload systemd
  command: systemctl daemon-reload

- name: Enable tmsrv service
  when: tmsrvservice|success
  service: name=tmsrv enabled=yes
  notify:
    - start tmsrv
